version: '3'

services:
  minetrack:
    image: augustinominh/minetrack
    restart: always
    volumes:
      - /opt/minevn/mc-tracker/minetrack/data:/usr/src/minetrack/data
    ports:
      - "8080:8080"
    networks:
      - minevn-web
